### PR TITLE
Add missing .gitkeep

### PR DESCRIPTION
**Pull request by drummond-work**
This is a proposed fix for https://github.com/hotwired/hotwire-rails-demo-chat/issues/1

We are missing `app/assets/javascripts/libraries.gitkeep` which causes errors when trying to start the app. 

This is generated when running `rails hotwire:install` with the `main` branch of `hotwired/stimulus-rails` in the Gemfile but it doesn't get created with the latest release on rubygems.org. Once `hotwire-stimulus-rails` gets re released this will always be auto created.

This PR just adds in that missing file to the sample repo.

```
➜  hotwire-rails-demo-chat git:(main) ✗ rails server
=> Booting Puma
=> Rails 6.1.0 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.1.1 (ruby 2.7.1-p83) ("At Your Service")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 11284
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/" for ::1 at 2020-12-22 13:57:00 -0500
   (0.9ms)  SELECT sqlite_version(*)
   (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by RoomsController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering rooms/index.html.erb within layouts/application
  Room Load (0.8ms)  SELECT "rooms".* FROM "rooms"
  ↳ app/views/rooms/index.html.erb:14
  Rendered rooms/index.html.erb within layouts/application (Duration: 8.1ms | Allocations: 996)
  Rendered layout layouts/application.html.erb (Duration: 52.3ms | Allocations: 10502)
Completed 500 Internal Server Error in 76ms (ActiveRecord: 0.8ms | Allocations: 14636)



ActionView::Template::Error (No such file or directory @ dir_initialize - ~/code/hotwire-rails-demo-chat/app/assets/javascripts/libraries):

app/assets/javascripts/importmap.json.erb:3:in `call'
```

### CODE REVIEW

**Comment by adammiribyan** [comment]
FYI, running `hotwire:install` adds the `/libraries` the directory.

**Comment by drummond-work** [comment]
Ah awesome! I tried that and it worked.

I guess the demo app should have a `app/assets/javascripts/libraries/.keep` file instead of removing the import?

**Comment by drnic** [comment]
Perhaps `rails hotwire:install` should create `app/assets/javascripts/libraries/.keep`, then it would be in this sample repo?

**Comment by drummond-work** [comment]
I think its already been fixed and new version of the gem just hasn't been published.

Adding the following to my `Gemfile` creates a `.gitkeep` file.

```
gem 'hotwire-stimulus-rails', github: 'hotwired/stimulus-rails', branch: 'main'
```

**Comment by drummond-work** [comment]
I updated the PR just to add that missing `.gitkeep`

**Pull request merged**
